#Motd text (uses vannila system, use this tool https://mctools.org/motd-creator)
First-line: A minecraft server

# From here remove # if you want to use a feature

#Potho link (use this if you want to change the photo at the same time as the server is running)

#link-to-photo: link

#If you want to change the max player count, (Only visual, not changing your player count)
#max-player-count: 420

#If you want to change the current player count, (Only visual)
#player-count: 69

#Hover text for player amount, max 6, (Only visual)
#plyer-list:
  #- steve

#Ping level graphics (0 = empty, 1=One bar, 2 = two bars, 3= tree bars, 4= four bars, 5= five bars, 6= six bars) (Only visual)
#ping-level: 6

#ping hover text, change the ms value (Only visual)
#ms-level: 1337



